### ISSUE TITLE
Automaticly set profiles

### ISSUE THREAD

**Issue by terminal-cs** [ThePBone/RootlessJamesDSP#110]
There should be an automatic detection system for profiles. E.g., when a profile is saved, it will be automatically applied when the audio output is switched to it. Also (like many other EQs), it should be able to detect different Bluetooth devices instead of just one profile for all of Bluetooth

**Comment by ThePBone** [comment]
This is already implemented but disabled by default. It can detect different Bluetooth devices and assigns one separate profile for each. 

You can go to 'Settings > Device profiles' to turn it on.

**Comment by terminal-cs** [comment]
> This is already implemented but disabled by default. It can detect different Bluetooth devices and assigns one separate profile for each.
> 
> You can go to 'Settings > Device profiles' to turn it on.

idk how I didn't see that 💀 
thanks
