### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by QkiZMR** [ThePBone/RootlessJamesDSP#113]
Is this project lack documentation? Or is there any?

**Comment by Albuslund** [comment]
I was just looking for a comprehensive or explanatory manual for settings and details on the different types of sound effects with which this project provides. Thank you for pointing out.

**Comment by ThePBone** [comment]
This project only contains documentation about the rootless implementation but not JamesDSP itself.

Check out the official JamesDSP repo for some more (official) info: https://github.com/james34602/JamesDSPManager
Documentation for JamesDSP's Liveprog script engine is available here: https://github.com/james34602/EEL_VM

There's also the official JDSP support group on Telegram. Questions about specific effects have already been answered there too in a more detailed manner. Try to use the message history search, if you're looking for something specific: https://t.me/jDSP_V4A
