### ISSUE TITLE
Using with VLC 


### ISSUE THREAD

**Issue by Albuslund** [ThePBone/RootlessJamesDSP#117]
Dear team of RootlessJamesDSP,

I am not quite sure if I am wrong or mistaken in my settings of VLC player, but I happen to have problems with playing audio files. For instance, after playing one track, the second doesn't produce sound, though it seems VLC is still working and playing the track. Maybe it is my phone, or the settings of VLC are off track. I paid attention not to use hardware acceleration options in the settings.

Thank you for your valuable work,

**Comment by ascendbeing** [comment]
Try vlc nightly? It's the 4.x codebase. https://code.videolan.org/videolan/vlc-android/-/pipelines click on the item then go to jobs and clicking the download button under the jobs list will download that targeted apk.

Nightly vlc is a bit rougher around the edges (ANRs can happen, usually it's related to media scanning/initial setup and then it'll mostly go away), but it has more advanced features that might make the difference here. I haven't tested it extensively myself. I just tried normal vlc (beta --you could opt into the vlc beta also, on play store, or download the latest beta APK off VLC ftp) and didn't notice anything myself.
So there's two things you can try: beta from play/ftp, or a nightly build for your arch.

**Comment by ascendbeing** [comment]
Try it in 1. Latest beta nightly for vlc or 2. Latest v4 trunk nightly
https://artifacts.videolan.org/vlc-android/
#2 corresponds to the directory for your arch with the "v4" in the name. #1 is based on the latest beta (google play opt into beta version + latest commits since that beta version)

**Comment by Albuslund** [comment]
> Try it in 0. Google play opt into beta 1. Latest beta nightly for vlc or 2. Latest v4 trunk nightly
> https://artifacts.videolan.org/vlc-android/
> #2 corresponds to the directory for your arch with the "v4" in the name. #1 is based on the latest beta (google play opt into beta version + latest commits since that beta version)

Thank you. It worked splendidly! I am using it with nightly version. 

Cheers,

**Comment by marscher** [comment]
The described problem is again blocking the usage of vlc, both nightly and version 3.5.4.

I can provide debug info, if desired.
