### ISSUE TITLE
[Root] App not Installed

### ISSUE THREAD

**Issue by doonoo** [ThePBone/RootlessJamesDSP#137]
The root version of this app doesn't install on my android 11 Jaguar ROM Oneplus 8
![Screenshot_20230707-150545_Package_installer](https://github.com/ThePBone/RootlessJamesDSP/assets/18385494/cf671781-ee84-4afe-a649-0bb8bb73b3fb)

**Comment by ThePBone** [comment]
You need to uninstall the official JamesDSP app that is bundled with the magisk package. It cannot be updated directly due to different app signatures.

Check the installation instructions here: https://github.com/ThePBone/RootlessJamesDSP/blob/master/BUILD_ROOT.md

**Comment by doonoo** [comment]
I did uninstall, just means I have to reboot after uninstall. I'll test that.

**Comment by doonoo** [comment]
No dice [...](https://youtu.be/iQyjYYZKEjs)

**Comment by ThePBone** [comment]
In that case, I'm not sure either. The installer isn't displaying any helpful information about the reason why it failed.

**Comment by ThePBone** [comment]
Purely guessing, but according to https://stackoverflow.com/a/52134971/11559090, some people fixed this by temporarily disabling Google Play Protect in the Play Store. It's also possible that your phone's storage is almost full.

**Comment by doonoo** [comment]
> Purely guessing, but according to https://stackoverflow.com/a/52134971/11559090, some people fixed this by temporarily disabling Google Play Protect in the Play Store. It's also possible that your phone's storage is almost full.

![Screenshot_20230707-190434_Settings](https://github.com/ThePBone/RootlessJamesDSP/assets/18385494/2e65c472-0df9-4dad-b5c9-9eaffb2dabad)
Disabled play protection and I just flashed the ROM so I know its not full. Is there a way through adb to debug the app to see how it installs?

**Comment by ThePBone** [comment]
Yes, you could install the APK using adb:

Using ADB via a computer:
```
adb install <path to adb file>
adb shell "logcat -d > /sdcard/log.txt"
```
Using ADB directly on the phone via Shizuku & Termux:
```
pm install <path to adb file>
logcat -d > /sdcard/log.txt
```

This will also create a file at `/sdcard/log.txt` with detailed logs; please upload that file if possible.

**Comment by doonoo** [comment]
> Yes, you could install the APK using adb using one of these methods:
> 
> Using ADB via a computer:
> 
> ```
> adb install <path to apk file on the computer>
> adb shell "logcat -d > /sdcard/log.txt"
> ```
> 
> Using ADB directly on the phone via Shizuku & Termux:
> 
> ```
> pm install <path to apk file on the phone>
> logcat -d > /sdcard/log.txt
> ```
> 
> This will also create a file at `/sdcard/log.txt` with detailed logs; please upload that file if possible.

Sorry I just got back. But installing it like that, it worked... Thanks
