### ISSUE TITLE
[Feature Request] Volume Normalizer

### ISSUE THREAD

**Issue by SunBreaker1** [ThePBone/RootlessJamesDSP#141]
With all the sound controls and effects, an option to normalize the playback volume would be a good complement to the already available options.

Personally, I'm an offline user, meaning I have music downloaded and use apps that control DSP and my library. The biggest problem with this is that every album has a different LUFS mastering level, meaning one song will be giod while the next will be loud and could cause hearing problems.

Adding a LUFS (industry standard) based normalizer could make sure that all played back songs/audio is at the same level without any explosive volume levels to damage hearing.

**Comment by blwckcore** [comment]
have you tried to use replaygain in your player?

**Comment by SunBreaker1** [comment]
> have you tried to use replaygain in your player?

Symphony does not have that option

**Comment by blwckcore** [comment]
well, I recommend you use other player like poweramp or aimp. or you can suggest the symphony developer to add replaygain to this player, I think it's not hard. I don't think, that James dsp will be able to do normalization by tracks and albums because it's real-time dsp. you need to analyze each song to know how loud it is. James DSP can't do that.

**Comment by SunBreaker1** [comment]
> well, I recommend you use other player like poweramp or aimp. or you can suggest the symphony developer to add replaygain to this player, I think it's not hard. I don't think, that James dsp will be able to do normalization by tracks and albums because it's real-time dsp. you need to analyze each song to know how loud it is. James DSP can't do that.

From my brief testing, the implementation of Replaygain in aimp is inconsistent. 

The main song I used; Bully - Calliope Mori and Replaygain 5db. The first few seconds of the song were unchanged and a little loud, then it slowly started to get quieter as the song progressed stabilizing at a lower volume. 

Tldr; starts loud then gets quieter 

I then tried with Replaygain off, and the volume stayed consistent throughout the song. Same thing happens with Boof Pack - Lord Aethelstan

**Comment by SunBreaker1** [comment]
> well, I recommend you use other player like poweramp or aimp. or you can suggest the symphony developer to add replaygain to this player, I think it's not hard. I don't think, that James dsp will be able to do normalization by tracks and albums because it's real-time dsp. you need to analyze each song to know how loud it is. James DSP can't do that.

Have you heard of TarsosDSP?

**Comment by ThePBone** [comment]
I'm only the developer of the rootless implementation; this repo only contains that. 

The actual DSP algorithms are maintained by James in a different repository: [james34602/JamesDSPManager](https://github.com/james34602/JamesDSPManager).
Please open an issue there instead, if you'd like to request new effects.
