### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by Lucky390163** [ThePBone/RootlessJamesDSP#155]
Please make limiter automatic, too, like poweramp, it is clipping in some peaky audio's.And do not remove manual limiter adjustment.

After the new update, dynamic range compression is not working.

**Comment by ThePBone** [comment]
I'm only the developer of the rootless implementation; this repo only contains that. The actual DSP algorithms are maintained by James in a different repository: [james34602/JamesDSPManager](https://github.com/james34602/JamesDSPManager). Please open an issue there instead, if you'd like to request new effects. 

Dynamic range compression has been removed in favour of the dynamic range commander. Those are different effects with different behaviour.

**Comment by Lucky390163** [comment]
At least can you maintain limiter to automatic it hurts ears sometimes
