### ISSUE TITLE
Could you share how you use the "WRITE_SECURE_SETTINGS" Permission?

### ISSUE THREAD

**Issue by firefoxlover** [ThePBone/RootlessJamesDSP#172]
First of all it would be really good to know for users how this is used. Is it to enable this internal audio stream?

There is [Better Internet Tiles](https://github.com/CasperVerswijvelt/Better-Internet-Tiles), an app that fixes how shit Android is, but needs root currently. If this could use it, that would be great.

So sharing this info would greatly benefit the app!

**Comment by ThePBone** [comment]
Hey, this app doesn't use `WRITE_SECURE_SETTINGS`. 

It only uses Shizuku to accelerate the first-launch setup process and to grant the special `DUMP` permission required to access debug information for some audio-related system services. 
Whether `WRITE_SECURE_SETTINGS` can be used for Better-Internet-Tiles depends on what APIs it needs to access.
