### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [ThePBone/RootlessJamesDSP#2]
Since the app is open source, would be nice to have it on F-Droid

**Comment by TheGamer1002** [comment]
Is it alright if I go through with this, @ThePBone?

**Comment by ThePBone** [comment]
@TheGamer1002 Sure! I don't have enough time to reliably maintain a F-Droid version myself.

**Comment by TheGamer1002** [comment]
Success! 🥳
