### ISSUE TITLE
Legacy not working with Bluetooth 

### ISSUE THREAD

**Issue by innit86** [ThePBone/RootlessJamesDSP#25]
So:

1. legacy mode on = bluetooth audio processing not working (see screenshot)
2. legacy mode off = bluetooth audio processing works but only with some apps (no youtube).

Pixel 7 Pro, Android 13 January firmware
Magisk canary 25.0 (25206)
Latest root JamesDSP 1.2.2 arm64
![Screenshot_20230225_071643~2](https://user-images.githubusercontent.com/58744017/221343284-af077db4-eb2c-42a3-a52d-d8f04d73f89c.jpg)

**Comment by ThePBone** [comment]
I have heard about this issue from other Google Pixel users that also use the original JDSP application on Android 13.

The new spatializer feature for Bluetooth headsets/earbuds causes Android to reject the JamesDSP effect engine in the global output session 0.
_________

I haven't tested this, but here is a possible fix that just disabled the spatializer:

Install a terminal emulator on your phone and execute these two commands. (requires root)
```
su
settings put secure spatial_audio_enabled 0  
```
Then you can just reboot your phone and see if it works now.

**Comment by innit86** [comment]
@TheGamer1002
su
settings put secure spatial_audio_enabled 0

Unfortunately this didn't make a difference.

**Comment by TheGamer1002** [comment]
> @TheGamer1002 

***I HAVE BEEN AWAKENED!***
---
Interesting. Now, I can only speak for myself as my headphones don't support spatial audio, and I haven't rooted my phone. Regardless, I can still help (hopefully)!
Go to settings > connected devices > [your headphones] > spatial audio and turn that off. Keep in mind I do not have a rooted phone.

If it still doesn't work, try going to Developer Settings and scrolling down to the Bluetooth section and fiddling with those options. Let me know the outcome!

**Comment by innit86** [comment]
> > @TheGamer1002
> 
> ## _**I HAVE BEEN AWAKENED!**_
> Interesting. Now, I can only speak for myself as my headphones don't support spatial audio, and I haven't rooted my phone. Regardless, I can still help (hopefully)! Go to settings > connected devices > [your headphones] > spatial audio and turn that off. Keep in mind I do not have a rooted phone.
> 
> If it still doesn't work, try going to Developer Settings and scrolling down to the Bluetooth section and fiddling with those options. Let me know the outcome!

Changing bluetooth settings one by one in developer settings, turning off spatial audio for every bluetooth headphones, running "su settings put secure spatial_audio_enabled 0" none of this worked.

**Comment by ThePBone** [comment]
Fixing legacy mode won't be possible because this appears to be a firmware issue. Legacy mode uses an Android feature that was [deprecated 11 years ago](https://issuetracker.google.com/issues/36936557), so it is not unexpected that it is starting to break on some devices.

However, I have rewritten the audio backend and added a new compatibility mode that allows JamesDSP to work correctly with all apps (YouTube, ...) even when legacy mode is disabled. That feature also enables you to exclude specific apps from being processed by JamesDSP.

1. Grab the updated APK here: https://github.com/ThePBone/RootlessJamesDSP/actions/runs/4283379993 
2. Disable legacy mode, enable 'enhanced processing' in settings, and grant the app root (or ADB) permission when requested.

**Comment by innit86** [comment]
> Fixing legacy mode won't be possible because this appears to be a firmware issue. Legacy mode uses an Android feature that was [deprecated 11 years ago](https://issuetracker.google.com/issues/36936557), so it is not unexpected that it is starting to break on some devices.
> 
> However, I have rewritten the audio backend and added a new compatibility mode that allows JamesDSP to work correctly with all apps (YouTube, ...) even when legacy mode is disabled. That feature also enables you to exclude specific apps from being processed by JamesDSP.
> 
> 1. Grab the updated APK here: https://github.com/ThePBone/RootlessJamesDSP/actions/runs/4283379993
> 2. Disable legacy mode, enable the new 'enhanced processing' option in settings, and grant the app root (or ADB) permission when requested.

Thanks a lot for taking the time to make it compatible with Pixel. The updated apk works perfectly now.
