### ISSUE TITLE
Universal (rootless+root) app

### ISSUE THREAD

**Issue by yhm3ps1jfp76nkd** [ThePBone/RootlessJamesDSP#3]
Would be nice if the app was universal and if it detected root it would install a root version of itself and otherwise proceed with a rootless setup

**Comment by ThePBone** [comment]
Unfortunately not possible because the root version contains some code that violates the Google Play terms of service. 
Also, I'm not actively developing + testing the root version, so I'll probably keep it as a separate binary for now.
