### ISSUE TITLE
Google Play Services and other non-FOSS dependencies

### ISSUE THREAD

**Issue by TheGamer1002** [ThePBone/RootlessJamesDSP#6]
Hey there,

In my process of F-Droid pushing, it looks like there’s Google Play dependencies and that’s not allowed in the F-Droid repo. What are they used for? Are there ways we can disable them?

**Comment by TheGamer1002** [comment]
I think some are used for crash reporting. Once I have a development environment, I’ll create a fork without those.

**Comment by ThePBone** [comment]
You also can add a new build flavor that excludes the Google Firebase/Crashlytics library in the `build.gradle.kts` file, if that's easier.
Example from another app on f-droid: https://github.com/Swordfish90/Lemuroid/blob/b6c824c651f538b7354835355f31676b7d01d117/lemuroid-app/build.gradle.kts#L53

**Comment by licaon-kter** [comment]
That would be nice, the current patch is huuuge and hampers autoupdating, ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12560

**Comment by ThePBone** [comment]
I added the new build flavor for F-Droid with commit 2d897c03754133b1a7ead30f5eb771ec1157c7ac.

The new gradle target can be called like this:
```
./gradlew assembleRootlessFdroidRelease
```
And should place the final APK here: `./app/build/outputs/apk/rootlessFdroid/release/JamesDSP-v1.1.1-rootless-fdroid-universal-release.apk`

Also, there's a shared library called `libcrashlytics-connector`. This is not part of crashlytics, but rather a helper library ([source code here](https://github.com/ThePBone/RootlessJamesDSP/tree/master/app/src/main/cpp/libcrashlytics-connector)) for easy logging from native code. In the F-Droid build, this library only outputs into logcat; anything else is removed at compile-time.

**Comment by ClockGen** [comment]
Thanks a lot @ThePBone. Does the fdroid build still send the crash logs in some other way, or the "send crash logs" switch in settings has no effect anymore?
If it sends logs and turned on by default we will have to add "Tracking" antifeature.

**Comment by ThePBone** [comment]
It does not send crash logs anymore. The 'Send crash logs' switch is hidden in the F-Droid build (and wouldn't have any functionality even if visible).

**Comment by licaon-kter** [comment]
This can be closed as the MR was merged :)

**Comment by TheGamer1002** [comment]
Success! 🥳
