### ISSUE TITLE
Root version 1.4.1 crash

### ISSUE THREAD

**Issue by pgrilo** [ThePBone/RootlessJamesDSP#67]
The Root version crashes trying to open the IRS file selection dialog/menu for the Convolver.

This issue was introduced on version 1.4.1, version 1.4.0 works perfecty.

Thanks for your awesome work!

**Comment by ThePBone** [comment]
Thanks for the report! 

The issue is fixed with Version 1.4.2. You can go to 'Settings > About > Check for updates' to pull the update directly in the app.
