### ISSUE TITLE
about custom recovery

### ISSUE THREAD

**Issue by bolbolfolfol** [ThePBone/RootlessJamesDSP#7]
Hi
can we flash something in twrp/ofox and make it work ?
and thank you

**Comment by ThePBone** [comment]
No, this app is specifically targeted toward devices without any modifications, such as root and custom recoveries. 

If you have an unlocked bootloader and want to use the root version of JamesDSP together with this app, you can find instructions for that here: https://github.com/ThePBone/RootlessJamesDSP/blob/master/BUILD_ROOT.md
