### ISSUE TITLE
Root Mode/Version

### ISSUE THREAD

**Issue by XMA2l** [ThePBone/RootlessJamesDSP#73]
To bypass the current limitations and maybe become able to get a little bit more flexible with the implementaion/potentially find a more (battery) efficient way, what do you think about integrating/building an alternative hook/version for rooted users? 

greetings and thx a lot for ur important work!

**Comment by coxackie** [comment]
Take a look at this:
https://github.com/ThePBone/RootlessJamesDSP/blob/master/BUILD_ROOT.md

**Comment by XMA2l** [comment]
> Take a look at this:
> https://github.com/ThePBone/RootlessJamesDSP/blob/master/BUILD_ROOT.md
> 

Thx a lot :) will this mess with my selinux? Thats my problem with viper ...
