### ISSUE TITLE
Monochrome themed icon

### ISSUE THREAD

**Issue by coxackie** [ThePBone/RootlessJamesDSP#8]
I know this is not the uttermost technical priority, but please consider adding a monochrome themed icon, introduced for A13. It will make the app blend much better in the home screen. (If you do so, please add it in the root variant as well, as I am using that on my rooted devices.)

**Comment by ThePBone** [comment]
Implemented with commit e39aa9782c4e47583a4534c9a842b042223f28c4. 
You can grab updated APKs here: https://github.com/ThePBone/RootlessJamesDSP/actions/runs/3850365748

**Comment by ThePBone** [comment]
Use this link instead: https://github.com/ThePBone/RootlessJamesDSP/actions/runs/3850436106
