### ISSUE TITLE
How to enable it to take effect automatically after startup？

### ISSUE THREAD

**Issue by linove** [ThePBone/RootlessJamesDSP#97]
I have to open this app every time I turn my phone on, and then click the button to enable the effect to make the dsp take effect. How can it take effect automatically when I turn the phone on?  Thank you so much

**Comment by ThePBone** [comment]
On the latest version, you can navigate to 'Settings > Miscellaneous' and check whether the permissions required to use auto-start are granted.
If this isn't the case, you need to tap on 'Grant optional permissions' and re-do the setup to grant these missing permissions.

After that's done, you will see a 'Launch after boot' option in 'Settings > Miscellaneous', which should be already enabled by default.
